services:
  db:
    image: postgres:17.4
    container_name: postgres_tp
    networks:
      - tp_network
    env_file:
      - ./.env
    ports:
      - "${DB_OUT_PORT}:5432"
    hostname: ${DB_HOST}
    volumes:
      - ./db_dumps:/dump/
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    
  backend:
    build:
      context: .
    container_name: python_tp
    command: uvicorn src.main:app --host 0.0.0.0 --port $PORT_BACK --workers 1 --reload
    depends_on:
      - db
    networks:
      - tp_network
    env_file:
      - ./.env
    ports:
      - "${PORT_BACK}:${PORT_BACK}"
    volumes:
      - ./:/srv
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://0.0.0.0:${PORT_BACK}/docs || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 10s

  frontend:
    build:
      context: ./front
    container_name: vue_tp
    command: npm run serve -- --port $PORT_FRONT
    env_file:
      - ./.env
    ports:
      - "${PORT_FRONT}:${PORT_FRONT}"
    networks:
      - tp_network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local

networks:
  tp_network:
    name: tp_network
    driver: bridge

  

