"""init

Revision ID: 0c2a7bb3ff76
Revises: c6b436c2a357
Create Date: 2025-04-15 01:41:53.037094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0c2a7bb3ff76'
down_revision: Union[str, None] = 'c6b436c2a357'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'user_type')
    op.add_column('user', sa.Column('user_type', sa.Enum('USER', 'PRO', 'MANAGER', 'ADMIN', name='usertype'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'user_type')
    op.add_column('profile', sa.Column('user_type', postgresql.ENUM('USER', 'PRO', 'MANAGER', 'ADMIN', name='usertype'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
