"""init

Revision ID: 9f283a5ba9a7
Revises: 65d5eaa301f8
Create Date: 2025-05-04 10:55:16.211140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9f283a5ba9a7'
down_revision: Union[str, None] = '65d5eaa301f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('players_cnt', sa.Enum('ONE', 'TWO', 'FIVE', name='teamplayerscnt'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team', 'players_cnt')
    # ### end Alembic commands ###
