"""user_profile_constraint

Revision ID: 1ae173072a4e
Revises: f2552e935d69
Create Date: 2025-04-01 05:03:15.206890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1ae173072a4e'
down_revision: Union[str, None] = 'f2552e935d69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_user_pair_freindship', 'friendslink', ['user_1_id', 'user_2_id'])
    op.create_unique_constraint('unique_user_pair_freindship_reverse', 'friendslink', ['user_2_id', 'user_1_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_pair_freindship_reverse', 'friendslink', type_='unique')
    op.drop_constraint('unique_user_pair_freindship', 'friendslink', type_='unique')
    # ### end Alembic commands ###
