"""hero

Revision ID: f769d7f4877d
Revises: f2a1dc4037f3
Create Date: 2025-04-06 03:39:15.937304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f769d7f4877d'
down_revision: Union[str, None] = 'f2a1dc4037f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hero', sa.Column('team_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'hero', 'team', ['team_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hero', type_='foreignkey')
    op.drop_column('hero', 'team_id')
    # ### end Alembic commands ###
