"""profiles_and_friends

Revision ID: 029228201b96
Revises: 2df95a82e10c
Create Date: 2025-04-01 02:34:08.123328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '029228201b96'
down_revision: Union[str, None] = '2df95a82e10c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_type', sa.Enum('USER', 'PRO', 'MANAGER', 'ADMIN', name='usertype'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('friendslink',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_1_id', sa.Integer(), nullable=False),
    sa.Column('user_2_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('user_1_id != user_2_id', name='check_not_self_freindship'),
    sa.ForeignKeyConstraint(['user_1_id'], ['profile.id'], ),
    sa.ForeignKeyConstraint(['user_2_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id', 'user_1_id', 'user_2_id'),
    sa.UniqueConstraint('user_1_id', 'user_2_id', name='unique_user_pair_freindship'),
    sa.UniqueConstraint('user_2_id', 'user_1_id', name='unique_user_pair_freindship_reverse')
    )
    op.add_column('user', sa.Column('profile_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'profile', ['profile_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'profile_id')
    op.drop_table('friendslink')
    op.drop_table('profile')
    # ### end Alembic commands ###
